### ISSUE TITLE
whats to root password of the vm ?

### ISSUE THREAD

**Issue by michabbb** [DECK36/plan9_workshop_tutorial#1]
thanks

**Comment by mschuett** [comment]
There is none.
You can log into the VM with `vagrant ssh`. User vagrant may use sudo without password.

**Comment by michabbb** [comment]
when i see the debian login console inside virtualbox - i can login (as usual).....and as usual, there is the root user....so i am a bit confused here.... in fact its a debian linux vm, and every linux has a root, so i don´t understand "there is none"...

**Comment by michabbb** [comment]
looked into /etc/shadow, of course there is root and of course root has a password, so please, what is it ? its a bit annoying to reset it, just because this info is not provided here ;(

**Comment by michabbb** [comment]
ok have seen what you are talking about... confusing when you have never worked with that vagrant stuff...
